import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Menu } from '@/components/menu'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex items-center justify-center w-screen h-screen`}
      >
        <main className="max-w-[1240px] h-[800px] mx-auto flex border dark:border-zinc-800 shadow-2xl shadow-zinc-900">
          <Menu />

          <div className="h-full w-[calc(100vw_-_24rem)]">{children}</div>
        </main>
      </body>
    </html>
  )
}
