import type { Metadata } from 'next'
import { Inter, Urbanist } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const urbanist = Urbanist({ subsets: ['latin'], variable: '--font-urbanist' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${urbanist.variable} antialiased flex overflow-hidden items-center justify-center w-screen h-screen`}
      >
        <main className="max-w-[1240px] h-[800px] mx-auto flex border dark:border-zinc-800 shadow-lg shadow-zinc-900">
          {/* <Menu /> */}

          <div className="h-[800px] w-[calc(100vw_-_24rem)] overflow-auto bg-zinc-900 relative">
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
